[2022-07-29 10:55:02,260] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Second_one.second_task scheduled__2021-12-28T00:00:00+00:00 [queued]>
[2022-07-29 10:55:02,277] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Second_one.second_task scheduled__2021-12-28T00:00:00+00:00 [queued]>
[2022-07-29 10:55:02,277] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 10:55:02,277] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-29 10:55:02,277] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 10:55:02,302] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): second_task> on 2021-12-28 00:00:00+00:00
[2022-07-29 10:55:02,307] {standard_task_runner.py:52} INFO - Started process 2922 to run task
[2022-07-29 10:55:02,312] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Second_one', 'second_task', 'scheduled__2021-12-28T00:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/Second_One.py', '--cfg-path', '/tmp/tmpr0konmn8', '--error-file', '/tmp/tmphpbb7y7s']
[2022-07-29 10:55:02,312] {standard_task_runner.py:80} INFO - Job 185: Subtask second_task
[2022-07-29 10:55:02,411] {task_command.py:369} INFO - Running <TaskInstance: Second_one.second_task scheduled__2021-12-28T00:00:00+00:00 [running]> on host 9f0f006fc89d
[2022-07-29 10:55:02,549] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yosr
AIRFLOW_CTX_DAG_ID=Second_one
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T00:00:00+00:00
[2022-07-29 10:55:02,550] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-29 10:55:02,551] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hello world']
[2022-07-29 10:55:02,564] {subprocess.py:85} INFO - Output:
[2022-07-29 10:55:02,567] {subprocess.py:92} INFO - hello world
[2022-07-29 10:55:02,567] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-29 10:55:02,632] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Second_one, task_id=second_task, execution_date=20211228T000000, start_date=20220729T105502, end_date=20220729T105502
[2022-07-29 10:55:02,692] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-29 10:55:02,737] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
