[2022-07-29 10:55:05,415] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Second_one.second_task scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-07-29 10:55:05,440] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Second_one.second_task scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-07-29 10:55:05,440] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 10:55:05,440] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-29 10:55:05,440] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 10:55:05,465] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): second_task> on 2022-01-01 00:00:00+00:00
[2022-07-29 10:55:05,474] {standard_task_runner.py:52} INFO - Started process 2947 to run task
[2022-07-29 10:55:05,477] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Second_one', 'second_task', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/Second_One.py', '--cfg-path', '/tmp/tmpo_r5vh3d', '--error-file', '/tmp/tmpge2xbs5v']
[2022-07-29 10:55:05,477] {standard_task_runner.py:80} INFO - Job 194: Subtask second_task
[2022-07-29 10:55:05,585] {task_command.py:369} INFO - Running <TaskInstance: Second_one.second_task scheduled__2022-01-01T00:00:00+00:00 [running]> on host 9f0f006fc89d
[2022-07-29 10:55:05,707] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yosr
AIRFLOW_CTX_DAG_ID=Second_one
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:00:00+00:00
[2022-07-29 10:55:05,708] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-29 10:55:05,709] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hello world']
[2022-07-29 10:55:05,723] {subprocess.py:85} INFO - Output:
[2022-07-29 10:55:05,725] {subprocess.py:92} INFO - hello world
[2022-07-29 10:55:05,726] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-29 10:55:05,770] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Second_one, task_id=second_task, execution_date=20220101T000000, start_date=20220729T105505, end_date=20220729T105505
[2022-07-29 10:55:05,819] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-29 10:55:05,866] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
