[2022-07-29 10:55:21,457] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Second_one.second_task scheduled__2022-01-20T00:00:00+00:00 [queued]>
[2022-07-29 10:55:21,474] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Second_one.second_task scheduled__2022-01-20T00:00:00+00:00 [queued]>
[2022-07-29 10:55:21,474] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 10:55:21,474] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-29 10:55:21,475] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 10:55:21,497] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): second_task> on 2022-01-20 00:00:00+00:00
[2022-07-29 10:55:21,504] {standard_task_runner.py:52} INFO - Started process 3077 to run task
[2022-07-29 10:55:21,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Second_one', 'second_task', 'scheduled__2022-01-20T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/Second_One.py', '--cfg-path', '/tmp/tmpzvz3161j', '--error-file', '/tmp/tmp_u9v65wo']
[2022-07-29 10:55:21,508] {standard_task_runner.py:80} INFO - Job 231: Subtask second_task
[2022-07-29 10:55:21,603] {task_command.py:369} INFO - Running <TaskInstance: Second_one.second_task scheduled__2022-01-20T00:00:00+00:00 [running]> on host 9f0f006fc89d
[2022-07-29 10:55:21,729] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yosr
AIRFLOW_CTX_DAG_ID=Second_one
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-20T00:00:00+00:00
[2022-07-29 10:55:21,730] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-29 10:55:21,731] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo hello world, ùi'm the second task and i'm going to run after the first task"]
[2022-07-29 10:55:21,744] {subprocess.py:85} INFO - Output:
[2022-07-29 10:55:21,747] {subprocess.py:92} INFO - hello world, ùim the second task and im going to run after the first task
[2022-07-29 10:55:21,748] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-29 10:55:21,795] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Second_one, task_id=second_task, execution_date=20220120T000000, start_date=20220729T105521, end_date=20220729T105521
[2022-07-29 10:55:21,852] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-29 10:55:21,895] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
